ROOT         := ../..

VS := RSep.v IO.v FS.v Net.v
# MODULES := $(VS:%.v=%)

# FS.vo: FS.v ../../src/coq/Ynot.vo ../../src/coq/Basis.vo ./IO.vo ./RSep.vo
# IO.vo: IO.v ../../src/coq/Ynot.vo ./RSep.vo
# Net.vo: Net.v ../../src/coq/Ynot.vo ./IO.vo ./FS.vo
# RSep.vo: RSep.v ../../src/coq/Ynot.vo


include ../Makefile.ynot
