#!/bin/bash
fname=main
# conv exaStrucBase
#getbib
bibtex $fname
latex $fname 
#| grep -v "Underfull" | grep -v "^$" \
#             | grep -v "/usr/share/texmf"
bibtex $fname
dvips -O 0in,0.7in -o $fname.ps $fname.dvi
ps2pdf $fname.ps
# dvips -o $fname.ps $fname.dvi
