
all:
	$(MAKE) -C Data
	$(MAKE) -C hello-world
	$(MAKE) -C fib-string
	$(MAKE) -C linked-list

clean:
	$(MAKE) -C Data clean
	$(MAKE) -C hello-world clean
	$(MAKE) -C fib-string clean
	$(MAKE) -C linked-list clean