
all:
	$(MAKE) -C Data
	$(MAKE) -C hello-world
	$(MAKE) -C fib-string
	$(MAKE) -C linked-list
	$(MAKE) -C Parse
	$(MAKE) -C IO

clean:
	$(MAKE) -C Data clean
	$(MAKE) -C Parse clean
	$(MAKE) -C IO clean
	$(MAKE) -C hello-world clean
	$(MAKE) -C fib-string clean
	$(MAKE) -C linked-list clean