#!/bin/bash

ensure_verifies()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then
    echo "*** ERROR: Benchmark ${2} expected to verify, but did not verify."
    exit -1
  else
    echo "PASSED Benchmark ${2}."
  fi
}

ensure_fails()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is text to display on failure.
  if [ "${1}" -ne "1" ]; then
    echo "*** SOUNDNESS ERROR ***************************************
    echo "*** SOUNDNESS ERROR: Benchmark ${2} expected to fail, but verified!"
    echo "*** SOUNDNESS ERROR ***************************************
    exit -1
  else
    echo "PASSED Benchmark ${2}."
  fi
}

TEST_SCRIPTS=$1

for s in $TEST_SCRIPTS; do
DIR=`dirname $s`
pushd $DIR > /dev/null
pwd
. run-tests
popd > /dev/null
done
echo "The test passed ! GO JAHOB !"
